# 此脚本用于获取${memDataDir}目录下所有jemalloc dump生成的heap文件；
# 并且将它们用jeprof工具分析生成txt形式报告
#!/bin/bash

set +e

dirPre=$(pwd)

plat=$1
if [ -n "$2" ]; then memDataDir=$2
else memDataDir="${dirPre}/memAnlys/${plat}"
fi

binaryFile="${dirPre}/bin/${plat}/lovely"
# jemalloc库文件路径
crossLibPrefix="/home/$USER/tool/jemalloc-dev/lib/${plat}/"
heapFileName=$(find ${memDataDir} -type f -name '*.heap' | head -n 1)
extension=".heap"
memReportDir="${dirPre}/memReport/${plat}/"

# 用rev反转文件路径字符串，以.作为定界符，选择进程号字段然后cut，最后再用rev命令将结果反转回来
pid=$(echo "${heapFileName}" | rev | cut -d '.' -f 4 | rev)

mkdir -p ${memReportDir}
rm -rf ${memReportDir}/*

# 查找目录下以.heap 结尾的文件
for heapFile in "${memDataDir}"/*"${extension}"; do
	pid_temp=$(echo "${heapFile}" | rev | cut -d '.' -f 4 | rev)
	if [[ ${pid_temp} != ${pid} ]]; then
		echo "Heap files are generated by different processes"
		exit 1
    fi

	dumpCount=$(echo "${heapFile}" | rev | cut -d '.' -f 3 | rev)

	# 用jeprof分析所有的heap文件；交叉编译时需要指定其他平台参数，如库路径，交叉编译工具链等
	jeprof --show_bytes ${binaryFile} ${heapFile} \
	--lib_prefix=${crossLibPrefix} \
	--text --cum \
	> ${memReportDir}/report_${dumpCount}.txt
done

python3 ${dirPre}/script/heapResMerge.py ${plat} ${memReportDir}
